### ISSUE TITLE
Can I export the render from PIXI?

### ISSUE THREAD

**Issue by nicokruger** [Prozi/pixi-shim#14] opened 2020-06-02 13:37 UTC
Hi there,

I can get the basic demo working, it prints the FPS and starts correctly and then exits after adding the bunny to the stage.

However, just curious, is there anyway I can export the image data in the canvas? I notice the note in the README:

   toDataURL: not ready yet (renders transparent image)

Which is what I get - I get blank PNG outputted from the example in tests/

Is there anyway I can export the render or dump the webgl context at all ?

**Comment by Prozi** [comment] 2020-07-20 00:04
this is not so easy and I had this discussion with one person already.

I would try to getContext('2d') and roll from there, then maybe and just maybe this could work (not on node webgl afaik)

if it would work and you'd like to submit some sample I would be grateful :beer:

**Comment by simonlourson** [comment] 2020-08-02 08:31
Hello, I tried to make this work with getContext('2d'). Here are the steps I have taken : 

In package.json: removed the dependency to node-gles. Replaced the dependency from pixi.js to pixi.js-legacy
In tests/index.json : 
replaced the lines :
```
const app = new PIXI.Application({ preserveDrawingBuffer: true });
console.log({ image, context: app.view.getContext('webgl2') });
```
with the lines : 
```
const app = new PIXI.Application({ forceCanvas: true, preserveDrawingBuffer: true });
console.log({ image, context: app.view.getContext('2d') });
```

Added the following code before app.render(): 
```
let graphics = new PIXI.Graphics();
graphics.beginFill(0x007AD9);
graphics.drawRect(100, 100, 600, 400);
graphics.endFill();

app.stage.addChild(graphics);
```

Here is the output from yarn test :
```
yarn run v1.12.1
$ node tests
pixi-shim ❤️ DOM
pixi-shim ❤️ Window 1024x768
pixi-shim ❤️ Canvas + WebGL
pixi-shim ❤️ polyfill performance.now
pixi-shim ❤️ polyfill requestAnimationFrame
pixi-shim ❤️ PIXI.js
{ getContext: { type: '2d', contextOptions: {} } }
{ getContext: { type: '2d', contextOptions: {} } }
{ getContext: { type: '2d', contextOptions: {} } }
{ getContext: { type: '2d', contextOptions: {} } }
{ getContext: { type: '2d', contextOptions: {} } }
pixi-shim ❤️ initialized in: 684.697ms
{ getContext: { type: '2d', contextOptions: { alpha: false } } }
{ getContext: { type: '2d', contextOptions: {} } }
{ getContext: { type: '2d', contextOptions: {} } }
{ getContext: { type: '2d', contextOptions: {} } }
{ getContext: { type: '2d', contextOptions: {} } }
PixiJS 5.3.2 - Canvas - http://www.pixijs.com/
{ 'PIXI.Application': true }
{ canvas: [Canvas 800x600] }
{ getContext: { type: '2d', contextOptions: {} } }
{
  image: HTMLImageElement {
    [Symbol(SameObject caches)]: [Object: null prototype] { style: [CSSStyleDeclaration] }
  },
  context: CanvasRenderingContext2D { canvas: [Canvas 800x600] }
}
{ 'sprite dimensions': { width: 1, height: 1 } }
{ 'PIXI.Sprite.from': true }
{ getContext: { type: '2d', contextOptions: {} } }
{ getContext: { type: '2d', contextOptions: {} } }
{
  base64: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAyAAAAJYCAIAAAAVFBUnAAAABmJLR0QA/wD/AP+gvaeTAAAJCElEQVR4nO3WSRGAABDAMMAMHhGAR9xgojPLkSjos8sCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAM+2Tge8ynFNFwDAnHOfLniNbToAAOBrDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQDEDBYAQMxgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwM/c/yIFIF/iGlgAAAAASUVORK5CYII=',
  toDataURL: true
}
{ FPS: '639.68' }
Done in 1.85s.
```

The results : the bunny texture is not showing at all in the dataurl generated. This seems to be because there is a problem with adding the image to the DOM? (the console.log for the image returns [Object: null prototype]). The sprite dimensions logged are also wrong ({ 'sprite dimensions': { width: 1, height: 1 } }).

However, the simple graphics tests I added (just adding a colored square in the center of the image) seems to be working.

I also tested generating the imageurl "internally" with pixi instead by replacing the line :
`const base64 = app.view.toDataURL("image/png", 1);`

With the follwoing code : 
```
let brt = new PIXI.BaseRenderTexture({width: 800, height: 600 })
let rt = new PIXI.RenderTexture(brt)
app.renderer.render(app.stage, rt, false)
const base64 = app.renderer.plugins.extract.canvas(rt).toDataURL()
```

Results are the same.

I would really like to be able to use pixi on my backend, and use textures as part of that (I can explain my use case if needed). Pixishim, is very useful for providing the polyfills, for window, image and canvas, if anybody has ideas to make this work with textures that would be awesome ! Thank you

**Comment by simonlourson** [comment] 2020-08-03 16:37
I have confirmed that when using pixijs-legacy, and working with the '2d' context, it is possible to export the resulting image to data url.

The main problem seems to be creating the textures from png or other image files. To solve this problem, I read my png files manually (using Jimp), and recreated my textures manually, using a graphics object and drawing rectangles pixel by pixel (graphics.drawRect(x, y, 1, 1)). The graphics objects is then rendered to a BaseRenderTarget, and this base render target can the be used as the texture for a sprite.

There are two problems with this approach. First, it is very slow. I have a about hundred spritesheets1(024x1024 png files) for my project. Reading all of them pixel by pixel and creating the render targets takes about 10 minutes.

The other problem is that it's very memory intensive. The png files for my project weight about 40Mb all together. When all my BaseTextures are created, and the graphics objects with each individual pixel disposed, the memory footprint of my node app is still about 2Gb. This seems way too high, even the raw bitmap data for my spritesheets would be about a quarter of that size.

The good news is that when the BaseTextures are created using this method, everything else seems to work without issue. My project is fairly complex, with a lot of tranforms, containers, tinting, an transparency of the sprites, and so far I haven't seen  any issues.

Right now I'm still looking for help to create the BaseTextures from my png files without the "graphics / pixel by pixel" hack. (For ideas on how to use this hack, you can refer to the getImage function in [this class](https://github.com/simonlourson/blueprintnotincluded-backend/blob/master/app/pixi-backend.ts), )

Thank you to anyone reading this who may be able to contribute

**Comment by Prozi** [comment] 2021-05-10 20:12
@simonlourson you could maybe improve that way if you load pictures from base64 (or doesnt it work at all even with pixijs-legacy?)

**Comment by Prozi** [comment] 2021-05-10 21:22
also @simonlourson if you have time can you try using what is desribed here

https://github.com/Prozi/pixi-shim#canvastodataurl since version 2.3.0 u should be able to use toDataURL()

good luck!

**Comment by Prozi** [comment] 2022-02-08 14:42
still no, see todays comment to https://github.com/Prozi/pixi-shim/issues/23

**Comment by Prozi** [comment] 2022-02-11 18:46
closing as working and tested (with simple sprites)

a bit hackish but works, see:

https://github.com/Prozi/pixi-shim/blob/master/pixi.spec.js
https://github.com/Prozi/pixi-shim/blob/master/to-data-url.js

**Closed by Prozi** 2022-02-11 18:46 UTC
